### ISSUE TITLE
[glommio] does it work?

### ISSUE THREAD

**Issue by kolbma** [ntex-rs/ntex#142]
no it doesn't... ;-)

```toml
# Cargo.toml
[package]
name = "glommio-test"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
ntex = { version = "0.5.27", features = ["glommio", "rustls", "url"] }
```

```rust
// src/main.rs

#[ntex::main]
async fn main() -> Result<(), std::io::Error> {
    Ok(())
}
```

```sh
$ RUST_BACKTRACE=full cargo r

    Finished dev [unoptimized + debuginfo] target(s) in 0.32s
     Running `target/debug/glommio-test`
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Custom { kind: InvalidData, error: "Incorrect source type!" }', /home/makolb/.cargo/registry/src/github.com-1ecc6299db9ec823/glommio-0.7.0/src/executor/mod.rs:1520:14
stack backtrace:
   0:     0x55ee728ead0d - std::backtrace_rs::backtrace::libunwind::trace::h9135f25bc195152c
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x55ee728ead0d - std::backtrace_rs::backtrace::trace_unsynchronized::h015ee85be510df51
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x55ee728ead0d - std::sys_common::backtrace::_print_fmt::h5fad03caa9652a2c
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/sys_common/backtrace.rs:66:5
   3:     0x55ee728ead0d - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h2b42ca28d244e5c7
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/sys_common/backtrace.rs:45:22
   4:     0x55ee7290682c - core::fmt::write::h401e827d053130ed
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/fmt/mod.rs:1198:17
   5:     0x55ee728e8781 - std::io::Write::write_fmt::hffec93268f5cde32
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/io/mod.rs:1672:15
   6:     0x55ee728ec4d5 - std::sys_common::backtrace::_print::h180c4c706ee1d3fb
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/sys_common/backtrace.rs:48:5
   7:     0x55ee728ec4d5 - std::sys_common::backtrace::print::hd0c35d18765761c9
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/sys_common/backtrace.rs:35:9
   8:     0x55ee728ec4d5 - std::panicking::default_hook::{{closure}}::h1f023310983bc730
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panicking.rs:295:22
   9:     0x55ee728ec1f1 - std::panicking::default_hook::h188fec3334afd5be
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panicking.rs:314:9
  10:     0x55ee728eca66 - std::panicking::rust_panic_with_hook::hf26e9d4f97b40096
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panicking.rs:698:17
  11:     0x55ee728ec957 - std::panicking::begin_panic_handler::{{closure}}::hfab912107608087a
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panicking.rs:588:13
  12:     0x55ee728eb204 - std::sys_common::backtrace::__rust_end_short_backtrace::h434b685ce8d9965b
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/sys_common/backtrace.rs:138:18
  13:     0x55ee728ec689 - rust_begin_unwind
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panicking.rs:584:5
  14:     0x55ee72652cd3 - core::panicking::panic_fmt::ha6dc7f2ab2479463
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/panicking.rs:142:14
  15:     0x55ee72652d63 - core::result::unwrap_failed::h42ad8e915aa0a906
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/result.rs:1814:5
  16:     0x55ee726b1e55 - core::result::Result<T,E>::unwrap::h07369350e655fa1e
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/result.rs:1107:23
  17:     0x55ee726f5a7d - <glommio::executor::LocalExecutor as core::default::Default>::default::h5b96318f94c9a781
                               at /home/makolb/.cargo/registry/src/github.com-1ecc6299db9ec823/glommio-0.7.0/src/executor/mod.rs:1518:9
  18:     0x55ee726547da - ntex_rt::glommio::block_on::he2613a9674b3c807
                               at /home/makolb/.cargo/registry/src/github.com-1ecc6299db9ec823/ntex-rt-0.4.6/src/lib.rs:23:18
  19:     0x55ee72659cb5 - ntex_rt::builder::block_on::hda206907e10982bd
                               at /home/makolb/.cargo/registry/src/github.com-1ecc6299db9ec823/ntex-rt-0.4.6/src/builder.rs:162:5
  20:     0x55ee72659724 - ntex_rt::builder::SystemRunner::block_on::h2de721a0c7320a17
                               at /home/makolb/.cargo/registry/src/github.com-1ecc6299db9ec823/ntex-rt-0.4.6/src/builder.rs:133:15
  21:     0x55ee7265d28e - glommio_test::main::ha7fb3ac792306e61
                               at /home/makolb/temp/glommio-test/src/main.rs:1:1
  22:     0x55ee7265e29b - core::ops::function::FnOnce::call_once::hd73b4527a59a9047
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/ops/function.rs:248:5
  23:     0x55ee72655ade - std::sys_common::backtrace::__rust_begin_short_backtrace::h2f9ab552ffb86684
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/sys_common/backtrace.rs:122:18
  24:     0x55ee72655b91 - std::rt::lang_start::{{closure}}::ha06663868ed023c4
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/rt.rs:145:18
  25:     0x55ee728e47de - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::hcdfee62722e5e4b8
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/ops/function.rs:280:13
  26:     0x55ee728e47de - std::panicking::try::do_call::h84ca51609826746f
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panicking.rs:492:40
  27:     0x55ee728e47de - std::panicking::try::hd58075e533b8e0cb
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panicking.rs:456:19
  28:     0x55ee728e47de - std::panic::catch_unwind::h1ebac24d83cb6ce2
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panic.rs:137:14
  29:     0x55ee728e47de - std::rt::lang_start_internal::{{closure}}::h0145388a1edd1640
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/rt.rs:128:48
  30:     0x55ee728e47de - std::panicking::try::do_call::h7630182e534a0a32
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panicking.rs:492:40
  31:     0x55ee728e47de - std::panicking::try::h05b6544f0c6331dc
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panicking.rs:456:19
  32:     0x55ee728e47de - std::panic::catch_unwind::h77b2ba8fd3309f34
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panic.rs:137:14
  33:     0x55ee728e47de - std::rt::lang_start_internal::h6612c8a7a6861b8b
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/rt.rs:128:20
  34:     0x55ee72655b60 - std::rt::lang_start::h0c93b7ca8bb95fb2
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/rt.rs:144:17
  35:     0x55ee7265d2ec - main
  36:     0x7f3f60a4329d - __libc_start_main
  37:     0x55ee72652f6a - _start
                               at /home/abuild/rpmbuild/BUILD/glibc-2.31/csu/../sysdeps/x86_64/start.S:120
  38:                0x0 - <unknown>
Panic in Arbiter thread.
```

```sh
$ cargo version -v
cargo 1.64.0 (387270bc7 2022-09-16)
release: 1.64.0
commit-hash: 387270bc7f446d17869c7f208207c73231d6a252
commit-date: 2022-09-16
host: x86_64-unknown-linux-gnu
libgit2: 1.4.2 (sys:0.14.2 vendored)
libcurl: 7.83.1-DEV (sys:0.4.55+curl-7.83.1 vendored ssl:OpenSSL/1.1.1q)
os: openSUSE 15.4 [64-bit]
```

**Comment by fakeshadow** [comment]
If you read the panic message you would know it comes from glommio crate which is out the control of ntex. ntex outsourcing the runtime to glommio and if you have problem related it's best you look into it's repo for answers.

If we specific to your issue it has to do with io_uring being a platform and version specific feature(only available on newer linux kernels) and it requires you have certain knowledge of the linux and io_uring configuration. The most possible solution is to config your [memlock](https://github.com/DataDog/glommio#supported-linux-kernels).
