### ISSUE TITLE
"A Tokio 1.x context was found, but timers are disabled. Call `enable_time` on the runtime builder to enable timers.

### ISSUE THREAD

**Issue by ctron** [ntex-rs/ntex#93]
Updating to the most recent ntex versions, it looks like Tokio timer support is missing. As ntex handles the tokio runtime creation, I am not sure how to perform a call to `Builder::enable_time`.

```
thread 'main' panicked at 'A Tokio 1.x context was found, but timers are disabled. Call `enable_time` on the runtime builder to enable timers.', /usr/src/.cargo-container-home/registry/src/github.com-1ecc6299db9ec823/tokio-1.11.0/src/time/driver/handle.rs:55:18
stack backtrace:
   0: rust_begin_unwind
             at ./rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panicking.rs:517:5
   1: core::panicking::panic_fmt
             at ./rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/core/src/panicking.rs:101:14
   2: core::option::expect_failed
             at ./rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/core/src/option.rs:1615:5
   3: tokio::time::interval::interval
   4: hyper::client::pool::PoolInner<T>::put
   5: <hyper::client::pool::Pooled<T> as core::ops::drop::Drop>::drop
   6: core::ptr::drop_in_place<hyper::client::pool::Pooled<hyper::client::client::PoolClient<reqwest::async_impl::body::ImplStream>>>
   7: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
   8: <hyper::client::client::ResponseFuture as core::future::future::Future>::poll
   9: <reqwest::async_impl::client::PendingRequest as core::future::future::Future>::poll
  10: <reqwest::async_impl::client::Pending as core::future::future::Future>::poll
  11: drogue_cloud_mqtt_endpoint::run::{{closure}}
  12: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  13: tokio::macros::scoped_tls::ScopedKey<T>::set
  14: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  15: tokio::macros::scoped_tls::ScopedKey<T>::set
  16: tokio::runtime::basic_scheduler::BasicScheduler<P>::block_on
  17: tokio::runtime::Runtime::block_on
  18: ntex_rt::tokio::block_on
  19: drogue_cloud_mqtt_endpoint::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Panic in Arbiter thread.

```

**Comment by ctron** [comment]
I noticed that ntex calls `enable_io` only. However, tokio already takes care of enabling only the necessary modules when calling `enable_all`. So the author of the application can control which modules get activated by using feature flags.

https://github.com/tokio-rs/tokio/blob/bcb968af8494d2808c2986104d6e67d0b276b1fe/tokio/src/runtime/builder.rs#L167-L174

I think ntex should revert to calling `enable_all`.

**Comment by fafhrd91** [comment]
ntex-rt 0.4.2 is released. I would suggest to use `ntex::time` (ntex_util::time) instead. tokio timers consumes a lot of memory, for me they look pretty useless
